CREATE TABLE IF NOT EXISTS `CONTACT_MSG` (
  `CONTACT_ID` INT AUTO_INCREMENT  PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SUBJECT` VARCHAR(100) NOT NULL,
  `MESSAGE` VARCHAR(500) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `HOLIDAYS` (
  `DAY` VARCHAR(20) NOT NULL,
  `REASON` VARCHAR(100) NOT NULL,
  `TYPE` VARCHAR(20) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL
);